00:
	loggedpy 00*.py
01:
	loggedpy 01*.py
02:
	loggedpy loggedpy-cat customized.py
03:
	loggedpy -m tokenize customized.py
04:
	loggedpy --flavor=./customized.py:Flavor 00*.py
05:
	loggedpy --flavor=./customized.py:Flavor 01*.py
06:
	loggedpy --flavor=./customized.py:Flavor loggedpy-cat customized.py
07:
	loggedpy --flavor=./customized.py:Flavor -m tokenize customized.py

