00:
	python hello.py
	loggedpy hello.py
01:
	loggedpy --loggedpy-driver=./customized.py:Driver hello.py
02:
	loggedpy -m tokenize --loggedpy-driver=./customized.py:Driver hello.py
03:
	loggedpy-cat hello.py
	loggedpy --loggedpy-driver=./customized.py:Driver loggedpy-cat hello.py
