00:
	python hello.py
	loggedpy hello.py
01:
	loggedpy --flavor=./customized.py:Flavor hello.py
02:
	loggedpy -m tokenize --flavor=./customized.py:Flavor hello.py
03:
	loggedpy-cat hello.py
	loggedpy --flavor=./customized.py:Flavor loggedpy-cat hello.py
